services:
  rembg:
    container_name: itemlens-rembg
    image: danielgatis/rembg
    command: s --no-ui
    environment:
      - OMP_NUM_THREADS=2
    ports:
      - "7000:7000"
    volumes:
      - ./rembg-data:/root/.rembg
    restart: unless-stopped

  paddleocr:
    container_name: itemlens-paddleocr
    build: ./paddleocr
    image: paddleocrfastapi:paddlejr
    environment:
      - TZ=Europe/Amsterdam
      - PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK=True
      - FLAGS_use_mkldnn=0
      - PADDLE_PDX_ENABLE_MKLDNN_BYDEFAULT=0
      - OMP_WAIT_POLICY=PASSIVE
      - OMP_NUM_THREADS=2
    ports:
      - "8000:8000"
    volumes:
      # Map host folder containing the model files to the container's cache path
      - ./paddleocr/downloads:/root/.paddleocr
      - ./paddleocr/paddlex_cache:/root/.paddlex
    restart: unless-stopped

  singlefile:
    container_name: itemlens-singlefile
    build: ./singlefile
    command: node webserver.js 8001
    ports:
      - "8001:8001"
    volumes:
      - ./singlefile:/opt/app
      - /opt/app/node_modules
    restart: unless-stopped
