<!-- src/lib/components/ItemHub.svelte -->
<script lang="ts">
    import MediaHub from "$lib/components/add/MediaHub.svelte";
    import ContainerSelector from "$lib/components/ContainerSelector.svelte";
    import QRurlScanner from "$lib/components/QRurlScanner.svelte";
    import AttributeAdder from "$lib/components/AttributeAdder.svelte";
    import RefreshDeleteList from "$lib/components/RefreshDeleteList.svelte";
    import { photoTypes } from "$lib/shared/constants";
    import { createEventDispatcher } from 'svelte';

    const dispatch = createEventDispatcher();

    export let containers = [];
    export let item: any = null;
    export let saving = false;

    // View state machine: 'hub', 'photos', 'location', 'links', 'details'
    let activeView = 'hub';

    // State for the Hub Badges
    let photoCount = item?.photos?.length || 0;
    let selectedLocations = item?.locations?.map(l => l.containerName) || [];
    let linkCount = item?.documents?.length || 0;

    let currentTitle = item?.title || "";
    let currentDescription = item?.description || "";
    let amount = item?.amount || "";
    let reason = item?.reason || "";
    let tagcsv = item?.tagcsv || "";

    let isAnalyzing = false;
    let pendingPhotos: any[] = [];
    
    // Default draft preview logic
    $: draftImagePath = pendingPhotos.length > 0 
        ? pendingPhotos[pendingPhotos.length - 1].localUrl 
        : item?.photos?.find(p => p.type === 'product')?.cropPath || item?.photos?.find(p => p.type === 'product')?.orgPath || "";

    let showAiDrawer = false;
    let userHint = "";
    let isRefining = false;
    let aiDialog: HTMLDialogElement;

    $: if (aiDialog) {
        if (showAiDrawer && !aiDialog.open) aiDialog.showModal();
        if (!showAiDrawer && aiDialog.open) aiDialog.close();
    }

    function handleAnalyzingStart(ev: any) {
        isAnalyzing = true;
    }

    function handleAnalyzingComplete(ev: any) {
        isAnalyzing = false;
        const data = ev.detail;
        if (data && data.aiData) {
            let autofilled = false;
            if (!currentTitle && data.aiData.title) {
                currentTitle = data.aiData.title;
                autofilled = true;
            }
            if (!currentDescription && data.aiData.description) {
                currentDescription = data.aiData.description;
                autofilled = true;
            }
            if (autofilled) {
                dispatch('success', 'AI auto-filled details!');
            }
        }
    }   

    function handlePendingChange(ev: any) {
        pendingPhotos = ev.detail;
        photoCount = (item?.photos?.length || 0) + pendingPhotos.length;
    }

    function changePendingType(index: number, newType: string) {
        // Find the hidden input generated by MultiImageUpload and force its value
        const hiddenInput = document.querySelector(`input[name="file.type.${index}"]`) as HTMLInputElement;
        if (hiddenInput) {
            hiddenInput.value = newType;
        }
        pendingPhotos = pendingPhotos.map(p => p.index === index ? { ...p, type: newType } : p);
    }

    async function runAiRefine() {
        if (!userHint.trim() || !draftImagePath) return;
        
        isRefining = true;
        try {
            let res;
            if (item?.id) {
                res = await fetch('/api/ai-refine', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ 
                        itemId: item.id,
                        hint: userHint 
                    })
                });
            } else {
                res = await fetch('/api/analyze-draft-refine', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ 
                        draftPath: draftImagePath,
                        hint: userHint 
                    })
                });
            }
            
            if (res.ok) {
                const result = await res.json();
                const aiData = result.aiData || result;
                if (aiData.title) currentTitle = aiData.title;
                if (aiData.description) currentDescription = aiData.description;
                showAiDrawer = false;
                userHint = "";
                dispatch('success', 'Item details enhanced by AI!');
            }
        } catch (e) {
            console.error(e);
        } finally {
            isRefining = false;
        }
    }
</script>

<div class="relative w-full md:max-w-2xl mx-auto overflow-hidden bg-base-100 min-h-[75vh] md:min-h-[80vh] md:rounded-[2rem] rounded-xl shadow-lg md:shadow-2xl border border-base-200">
    
    <!-- ================= THE HUB VIEW ================= -->
    <div class="absolute inset-0 pb-24 transition-transform duration-300 ease-in-out p-4 sm:p-8 overflow-y-auto {activeView === 'hub' ? 'translate-x-0' : '-translate-x-full'}">
        <div class="text-center mb-8">
            <h2 class="text-2xl font-bold">{currentTitle || (item ? 'Edit Item' : 'New Item')}</h2>
            <p class="text-gray-500 text-sm">
                {#if isAnalyzing}
                    <span class="loading loading-spinner loading-xs text-primary align-middle mr-1"></span> AI is analyzing...
                {:else}
                    {item ? 'Update sections below' : 'Tap camera to start, or select a section below'}
                {/if}
            </p>
        </div>

        <!-- HERO CAMERA BUTTON (Pure 1-Tap Capture) -->
        <div class="flex justify-center mb-4 relative">
            <button type="button" class="btn btn-primary btn-circle h-28 w-28 shadow-xl hover:scale-105 transition-transform overflow-hidden p-0" aria-label="Quick Take Photo"
                on:click={() => {
                    const fileInputs = document.querySelectorAll('input[type="file"][name^="file."]');
                    const fileInput = fileInputs[fileInputs.length - 1] as HTMLInputElement;
                    const typeInputs = document.querySelectorAll('input[type="hidden"][name^="file.type."]');
                    const typeInput = typeInputs[typeInputs.length - 1] as HTMLInputElement;
                    if (fileInput && typeInput) {
                        typeInput.value = 'product'; // Default to product, AI will correct if it's a receipt
                        fileInput.click();
                    }
                }}>
                {#if pendingPhotos.length > 0 && pendingPhotos[pendingPhotos.length - 1].isAnalyzing}
                    <div class="absolute inset-0 bg-base-100/60 backdrop-blur-sm flex items-center justify-center z-10">
                        <span class="loading loading-spinner loading-lg text-primary"></span>
                    </div>
                {/if}
                
                {#if draftImagePath}
                    <img src={draftImagePath} alt="Preview" class="w-full h-full object-cover" />
                {:else}
                    <i class="bi bi-camera text-5xl"></i>
                {/if}
            </button>
            {#if photoCount > 0}
                <div class="absolute top-0 md:right-[35%] right-[25%] bg-success text-white rounded-full w-8 h-8 flex items-center justify-center font-bold shadow-md border-2 border-base-100 z-10 pointer-events-none">
                    <i class="bi bi-check-lg"></i>
                </div>
            {/if}
        </div>

        <!-- RECENT CAPTURES FILMSTRIP -->
        {#if pendingPhotos.length > 0}
            <div class="flex gap-3 overflow-x-auto py-2 mb-8 max-w-lg mx-auto snap-x hide-scrollbar">
                {#each pendingPhotos as photo}
                    <div class="relative w-20 h-20 shrink-0 rounded-xl overflow-hidden shadow-sm border border-base-200 snap-center bg-base-200 group">
                        <img src={photo.localUrl} class="w-full h-full object-cover" alt="Captured" />
                        {#if photo.isAnalyzing}
                            <div class="absolute inset-0 bg-base-100/50 flex items-center justify-center">
                                <span class="loading loading-spinner loading-sm text-primary"></span>
                            </div>
                        {:else}
                            <div class="absolute bottom-0 w-full opacity-90 group-hover:opacity-100 transition-opacity">
                                <select 
                                    class="select select-xs w-full bg-base-300 text-base-content border-none focus:outline-none rounded-none text-[10px] h-6 min-h-0 px-1 font-semibold"
                                    value={photo.type}
                                    on:change={(e) => changePendingType(photo.index, e.currentTarget.value)}
                                >
                                    <option value="product">Product</option>
                                    <option value="invoice or receipt">Receipt</option>
                                    <option value="information">Info</option>
                                    <option value="other">Other</option>
                                </select>
                            </div>
                        {/if}
                    </div>
                {/each}
            </div>
        {/if}

        <div class="flex flex-col gap-3 max-w-lg mx-auto {!pendingPhotos.length ? 'mt-10' : ''}">
            <button type="button" class="btn btn-outline h-auto py-4 px-4 w-full flex justify-between items-center rounded-xl border-base-300 hover:border-primary hover:bg-base-50" on:click={() => activeView = 'photos'}>
                <div class="flex items-center gap-4">
                    <div class="bg-blue-100 text-blue-600 w-12 h-12 rounded-full flex items-center justify-center text-xl shrink-0">
                        <i class="bi bi-camera"></i>
                    </div>
                    <div class="text-left">
                        <div class="font-bold text-base">Photos</div>
                        <div class="text-xs text-gray-500 font-normal">Upload or fetch</div>
                    </div>
                </div>
                <div class="flex items-center gap-2">
                    {#if photoCount > 0}
                        <span class="badge badge-primary">{photoCount}</span>
                    {/if}
                    <i class="bi bi-chevron-right text-gray-400"></i>
                </div>
            </button>

            <button type="button" class="btn btn-outline h-auto py-4 px-4 w-full flex justify-between items-center rounded-xl border-base-300 hover:border-primary hover:bg-base-50" on:click={() => activeView = 'location'}>
                <div class="flex items-center gap-4">
                    <div class="bg-purple-100 text-purple-600 w-12 h-12 rounded-full flex items-center justify-center text-xl shrink-0">
                        <i class="bi bi-box-seam"></i>
                    </div>
                    <div class="text-left">
                        <div class="font-bold text-base">Location</div>
                        <div class="text-xs text-gray-500 font-normal">Scan QR or select</div>
                    </div>
                </div>
                <div class="flex items-center gap-1 flex-wrap justify-end">
                    {#if selectedLocations.length > 0}
                        {#each selectedLocations.slice(0,2) as loc}
                            <span class="badge badge-primary badge-sm font-mono">{loc}</span>
                        {/each}
                        {#if selectedLocations.length > 2}
                            <span class="badge badge-primary badge-sm">+{selectedLocations.length - 2}</span>
                        {/if}
                    {/if}
                    <i class="bi bi-chevron-right text-gray-400 ml-1"></i>
                </div>
            </button>

            <button type="button" class="btn btn-outline h-auto py-4 px-4 w-full flex justify-between items-center rounded-xl border-base-300 hover:border-primary hover:bg-base-50" on:click={() => activeView = 'links'}>
                <div class="flex items-center gap-4">
                    <div class="bg-emerald-100 text-emerald-600 w-12 h-12 rounded-full flex items-center justify-center text-xl shrink-0">
                        <i class="bi bi-link-45deg"></i>
                    </div>
                    <div class="text-left">
                        <div class="font-bold text-base">Documents</div>
                        <div class="text-xs text-gray-500 font-normal">Manual or scan QR</div>
                    </div>
                </div>
                <div class="flex items-center gap-2">
                    {#if linkCount > 0}
                        <span class="badge badge-primary">{linkCount}</span>
                    {/if}
                    <i class="bi bi-chevron-right text-gray-400"></i>
                </div>
            </button>
            
            <button type="button" class="btn btn-outline h-auto py-4 px-4 w-full flex justify-between items-center rounded-xl border-base-300 hover:border-primary hover:bg-base-50" on:click={() => activeView = 'details'}>
                <div class="flex items-center gap-4">
                    <div class="bg-orange-100 text-orange-600 w-12 h-12 rounded-full flex items-center justify-center text-xl shrink-0">
                        <i class="bi bi-pencil-square"></i>
                    </div>
                    <div class="text-left">
                        <div class="font-bold text-base">Item Details</div>
                        <div class="text-xs text-gray-500 font-normal">Title, qty, tags...</div>
                    </div>
                </div>
                <i class="bi bi-chevron-right text-gray-400"></i>
            </button>
        </div>
    </div>

    <!-- ================= SUB-VIEWS ================= -->

    <!-- PHOTOS VIEW -->
    <div class="absolute inset-0 transition-transform duration-300 ease-in-out bg-base-100 flex flex-col {activeView === 'photos' ? 'translate-x-0' : 'translate-x-full'}">
        <div class="flex items-center p-4 sm:p-6 pb-2">
            <button type="button" class="btn btn-circle btn-ghost bg-base-200" aria-label="Back to Hub" on:click={() => activeView = 'hub'}><i class="bi bi-arrow-left text-xl"></i></button>
            <h2 class="text-xl font-bold ml-4">Photos</h2>
        </div>
        <div class="flex-1 overflow-y-auto px-2 sm:px-6 pb-6">
            <div class="max-w-lg mx-auto w-full">
                <MediaHub 
                    photoTypes={photoTypes} 
                    photoValues={item?.photos || []}
                    on:success={(ev) => dispatch('success', ev.detail)} 
                    on:analyzingStart={handleAnalyzingStart}
                    on:analyzingComplete={handleAnalyzingComplete}
                    on:pendingChange={handlePendingChange}
                />
            </div>
        </div>
        <div class="p-4 sm:p-6 bg-base-100 border-t border-base-200">
            <button type="button" class="btn btn-neutral btn-lg w-full max-w-lg mx-auto block rounded-xl shadow-sm" on:click={() => activeView = 'hub'}><i class="bi bi-check2-circle mr-2"></i> Done</button>
        </div>
    </div>

    <!-- LOCATION VIEW -->
    <div class="absolute inset-0 transition-transform duration-300 ease-in-out bg-base-100 flex flex-col {activeView === 'location' ? 'translate-x-0' : 'translate-x-full'}">
        <div class="flex items-center p-4 sm:p-6 pb-2">
            <button type="button" class="btn btn-circle btn-ghost bg-base-200" aria-label="Back to Hub" on:click={() => activeView = 'hub'}><i class="bi bi-arrow-left text-xl"></i></button>
            <h2 class="text-xl font-bold ml-4">Storage Location</h2>
        </div>
        <div class="flex-1 overflow-y-auto px-2 sm:px-6 pb-6">
            <div class="max-w-lg mx-auto w-full">
                <ContainerSelector 
                    containers={containers} 
                    values={item?.locations || []}
                    on:success={(ev) => dispatch('success', ev.detail)}
                    on:change={(ev) => selectedLocations = ev.detail.containers}
                />
            </div>
        </div>
        <div class="p-4 sm:p-6 bg-base-100 border-t border-base-200">
            <button type="button" class="btn btn-neutral btn-lg w-full max-w-lg mx-auto block rounded-xl shadow-sm" on:click={() => activeView = 'hub'}><i class="bi bi-check2-circle mr-2"></i> Done</button>
        </div>
    </div>

    <!-- LINKS VIEW -->
    <div class="absolute inset-0 transition-transform duration-300 ease-in-out bg-base-100 flex flex-col {activeView === 'links' ? 'translate-x-0' : 'translate-x-full'}">
        <div class="flex items-center p-4 sm:p-6 pb-2">
            <button type="button" class="btn btn-circle btn-ghost bg-base-200" aria-label="Back to Hub" on:click={() => activeView = 'hub'}><i class="bi bi-arrow-left text-xl"></i></button>
            <h2 class="text-xl font-bold ml-4">Documents</h2>
        </div>
        <div class="flex-1 overflow-y-auto px-2 sm:px-6 pb-6">
            <div class="max-w-lg mx-auto w-full">
                {#if item?.documents?.length > 0}
                    <div class="mb-6 bg-base-50/50 p-4 rounded-xl border border-base-200">
                        <h3 class="font-semibold text-sm text-gray-500 mb-3 flex items-center gap-2"><i class="bi bi-file-earmark-text"></i> Existing Documents</h3>
                        <RefreshDeleteList
                            values={item.documents}
                            inputName="documents"
                            columns={{
                                "3":{name:"Title",     fieldName:"title", isImage: false},
                                "4":{name:"Filename", fieldName:"path", isLink: true}
                            }}
                        />
                    </div>
                {/if}
                <QRurlScanner 
                    on:success={(ev) => dispatch('success', ev.detail)}
                    on:change={(ev) => linkCount = (item?.documents?.length || 0) + ev.detail.count}
                    on:processingStart={(ev) => dispatch('processingStart', ev.detail)}
                    on:processingComplete={(ev) => dispatch('processingComplete', ev.detail)}
                />
            </div>
        </div>
        <div class="p-4 sm:p-6 bg-base-100 border-t border-base-200">
            <button type="button" class="btn btn-neutral btn-lg w-full max-w-lg mx-auto block rounded-xl shadow-sm" on:click={() => activeView = 'hub'}><i class="bi bi-check2-circle mr-2"></i> Done</button>
        </div>
    </div>

    <!-- DETAILS VIEW -->
    <div class="absolute inset-0 transition-transform duration-300 ease-in-out bg-base-100 flex flex-col {activeView === 'details' ? 'translate-x-0' : 'translate-x-full'}">
        <div class="flex items-center p-4 sm:p-6 pb-2">
            <button type="button" class="btn btn-circle btn-ghost bg-base-200" aria-label="Back to Hub" on:click={() => activeView = 'hub'}><i class="bi bi-arrow-left text-xl"></i></button>
            <h2 class="text-xl font-bold ml-4">Item Details</h2>
        </div>

        <div class="flex-1 overflow-y-auto px-4 sm:px-6 pb-6">
            <div class="flex flex-col gap-5 max-w-lg mx-auto w-full">
                <div class="form-control w-full">
                    <div class="label">
                        <span class="label-text font-semibold flex items-center gap-2">
                            Title
                            {#if isAnalyzing}
                                <span class="loading loading-spinner loading-xs text-primary"></span>
                                <span class="text-xs text-primary font-normal">AI analyzing image...</span>
                            {/if}
                        </span>
                    </div>
                    <div class="relative w-full">
                        <input type="text" name="title" bind:value={currentTitle} placeholder="Leave blank for AI auto-fill..." class="input input-bordered w-full pr-12 rounded-xl" class:input-primary={isAnalyzing}>
                        {#if draftImagePath}
                            <button type="button" class="absolute right-3 top-3 text-primary/70 hover:text-primary transition-colors" title="Refine with AI" on:click={() => showAiDrawer = true}>
                                <i class="bi bi-stars text-xl"></i>
                            </button>
                        {/if}
                    </div>
                </div>

                <div class="form-control w-full">
                    <div class="label"><span class="label-text font-semibold">Description</span></div>
                    <textarea name="description" bind:value={currentDescription} rows="3" placeholder="Notes (Markdown supported)..." class="textarea textarea-bordered w-full rounded-xl" class:textarea-primary={isAnalyzing}></textarea>
                </div>

                <div class="grid grid-cols-2 gap-4">
                    <div class="form-control w-full">
                        <div class="label"><span class="label-text font-semibold">Amount</span></div>
                        <input type="number" name="amount" bind:value={amount} placeholder="1" class="input input-bordered w-full rounded-xl">
                    </div>
                    <div class="form-control w-full">
                        <div class="label"><span class="label-text font-semibold">Reason</span></div>
                        <input type="text" name="reason" bind:value={reason} placeholder="Project Apollo" class="input input-bordered w-full rounded-xl">
                    </div>
                </div>

                <div class="form-control w-full">
                    <div class="label"><span class="label-text font-semibold">Tags</span></div>
                    <input type="text" name="tagcsv" bind:value={tagcsv} placeholder="electronics, office, spare..." class="input input-bordered w-full rounded-xl">
                    <div class="label"><span class="label-text-alt text-gray-400">Separated by comma.</span></div>
                </div>

                <div class="form-control w-full">
                    <div class="label"><span class="label-text font-semibold">Attributes</span></div>
                    <div class="bg-base-200/50 p-3 rounded-xl border border-base-200">
                        <AttributeAdder values={item?.attributes || []} />
                    </div>
                </div>
            </div>
        </div>
        
        <div class="p-4 sm:p-6 bg-base-100 border-t border-base-200">
            <button type="button" class="btn btn-neutral btn-lg w-full max-w-lg mx-auto block rounded-xl shadow-sm" on:click={() => activeView = 'hub'}><i class="bi bi-check2-circle mr-2"></i> Done</button>
        </div>
    </div>

    <!-- ================= STICKY FOOTER ================= -->
    <div class="absolute bottom-0 left-0 w-full p-4 bg-base-100/90 backdrop-blur-md border-t border-base-200 z-50">
        <button disabled={saving} type="submit" class="btn btn-primary btn-lg w-full max-w-lg mx-auto block rounded-xl shadow-md">
            {#if saving}
                <span class="loading loading-spinner"></span> Saving...
            {:else}
                <i class="bi bi-save mr-2 text-xl"></i> {item ? 'Save Changes' : 'Save Item'}
            {/if}
        </button>
    </div>
</div>

<style>
    /* Utility class for hiding scrollbars on the filmstrip */
    .hide-scrollbar::-webkit-scrollbar {
        display: none;
    }
    .hide-scrollbar {
        -ms-overflow-style: none; 
        scrollbar-width: none; 
    }
</style>

<!-- The Bottom Drawer for AI Refinement -->
<dialog bind:this={aiDialog} class="modal modal-bottom sm:modal-middle" on:close={() => showAiDrawer = false}>
    <div class="modal-box w-full max-w-[95vw] sm:max-w-md mx-auto p-6 bg-base-100/95 backdrop-blur-xl rounded-t-3xl sm:rounded-3xl overflow-hidden">
        <h3 class="font-bold text-xl mb-2 flex items-center gap-2">
            <i class="bi bi-stars text-primary"></i> Refine AI Guess
        </h3>
        <p class="text-sm text-gray-500 mb-6">Give the AI a nudge with a brand or model name to get a better match.</p>
        
        <input type="text" bind:value={userHint} on:keydown={(e) => e.key === 'Enter' && runAiRefine()} placeholder="e.g. It's actually a MITTZON desk" class="input input-bordered w-full rounded-xl mb-4" />
        
        <div class="modal-action mt-0 flex gap-2">
            <button type="button" class="btn btn-ghost rounded-xl flex-1" on:click={() => showAiDrawer = false}>Cancel</button>
            <button type="button" class="btn btn-primary rounded-xl flex-1 shadow-md" on:click={runAiRefine} disabled={isRefining}>
                {#if isRefining}
                    <span class="loading loading-spinner"></span>
                {:else}
                    Enhance
                {/if}
            </button>
        </div>
    </div>
    <div class="modal-backdrop">
        <button type="button" on:click={() => showAiDrawer = false}>close</button>
    </div>
</dialog>